# exception_obj.py - Example of using an exception object

try:
    1 / 0
except Exception as e:
    print("Exception occurred:", e)
